### ISSUE TITLE
Register process feedback

### ISSUE THREAD

**Issue by yolimarmarin** [GiomarOsorio/another-e-learning-platform#2]
When a user is filling the registration form, the feedback of an invalid field should be given in real-time, meaning the user shouldn't have to click `register` to see which fields are invalid, they should be able to see that while they are filling the form. (Again, not a bug, this is just UX related)

On another note, it would be cool to add options to register with Google and Facebook (This is just something good to take into consideration for future improvements)

**Comment by GiomarOsorio** [comment]
feature added in commit [https://github.com/GiomarOsorio/another-e-learning-platform/commit/f3989bdf6ac1107f5ce20cdcd8e8378127f73459](#89332fa), thanks!.
